--Users table to keep track of users
create table
  public.users (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default (now() at time zone 'pdt'::text),
    user_name text not null,
    password_hash text not null,
    constraint users_pkey primary key (id),
    constraint users_user_name_key unique (user_name)
  ) tablespace pg_default;

  --Posts table for posts to be created
  create table
  public.posts (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    author bigint null,
    message text null,
    private boolean null default true,
    constraint posts_pkey primary key (id),
    constraint posts_author_fkey foreign key (author) references users (id)
  ) tablespace pg_default;

  --Replies table for replies to posts
  create table
  public.replies (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    post_id bigint null,
    author bigint null,
    message text null,
    constraint replies_pkey primary key (id),
    constraint replies_author_fkey foreign key (author) references users (id),
    constraint replies_post_id_fkey foreign key (post_id) references posts (id)
  ) tablespace pg_default;

  --Tags table for tags that are used on posts
  create table
  public.tags (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    tag text not null,
    constraint tags_pkey primary key (id),
    constraint tags_tag_key unique (tag)
  ) tablespace pg_default;

-- Tag relations table for keeping track of what tags are on what posts
create table
  public.tag_relations (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    post_id bigint null,
    tag_id bigint null,
    constraint tag_relations_pkey primary key (id),
    constraint tag_relations_post_id_fkey foreign key (post_id) references posts (id),
    constraint tag_relations_tag_id_fkey foreign key (tag_id) references tags (id)
  ) tablespace pg_default;